name: "Emoji List Updater"

on:
  workflow_dispatch:
  push:
    paths: 
      - .github/scripts/markdown.php
    branches: 
      - main

jobs:
  readme_generator:
    name: "Emoji Readme Generator"
    runs-on: ubuntu-latest
    steps:
      - name: "📥  Fetching Repository Contents"
        uses: actions/checkout@master

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
      - name: Render Markdown   
        run: php .github/scripts/markdown.php
      - name: Push To Github
        run: |
          git config --global user.email "githubactionbot@gmail.com"
          git config --global user.name "Github Action Bot"
          git add README.md -f
          git add index.html -f
          if [ "$(git status --porcelain)" != "" ]; then
            git commit -m "💬 - Emoji Updated"
          fi
        
          git push "https://x-access-token:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
