name: "Emoji List Updater"

on:
  workflow_dispatch:

jobs:
  readme_generator:
    name: "Emoji Readme Generator"
    runs-on: "ubunut-latest"
    steps:
      - name: "📥  Fetching Repository Contents"
        uses: actions/checkout@master

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
      - name: Render Markdown   
        run: php .github/scripts/markdown.php
